.TH oversea-stage 1 "OverSea CLI man page"
.SH NAME
oversea-stage - OverSea stage related commands.

.SH SYNOPSIS
oversea stage <command>

.SH DESCRIPTION
Commands for running and showing OverSea stage steps

.SH COMMANDS
.B run
.RS
Runs a OverSea stage and shows its execution progress. See
.BR oversea-stage-run(1)


.RE
.B dry-run
.RS
Shows the execution steps of a OverSea stage. See
.BR oversea-stage-show(1)
